FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_DJANGO_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_DJANGO_API_URL=$NEXT_PUBLIC_DJANGO_API_URL

RUN npm run build

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Runtime env vars (needed by API routes)
ARG DJANGO_API_URL
ARG OPENAI_API_KEY
ARG OPENROUTER_API_KEY
ARG OWNER_EMAIL
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_SECURE
ARG SMTP_USER
ARG SMTP_PASS
ENV DJANGO_API_URL=$DJANGO_API_URL
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ENV OWNER_EMAIL=$OWNER_EMAIL
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_SECURE=$SMTP_SECURE
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS

EXPOSE 3000

CMD ["npm", "start"]